spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?userUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 

  application:
    name: adk_blog
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    lettuce:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      table-prefix: bl_

# 内网访问 就需要改成内网来进行
aliyun:
  accessKeyId: your keyId
  accessKeySecret: your keysecret
  endpoint: your endpoint #开发环境直接使用公网上传图片
  bucketName: your bucketName
server:
  port: 4567
bangumi:
  api: https://api.bgm.tv
  agent: your agent

fileabsolutepath: D:\
ossurl: your oss url 
sitemapPath:  D:\
baseUrl: your website