spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adkblog?userUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 123456
    password: 

  application:
    name: adk_blog
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    lettuce:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      table-prefix: bl_

aliyun:
  accessKeyId: 
  accessKeySecret: 
  endpoint: 
  bucketName: 
server:
  port: 12345